name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v4

      - name: pnpm install
        run: pnpm --dir frontend install --frozen-lockfile

      - name: pnpm build
        run: pnpm --dir frontend build

      - name: go tool templ generate
        run: go tool templ generate

      - name: go tool lint
        run: go tool lint ./...

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v4

      - name: pnpm install
        run: pnpm --dir frontend install --frozen-lockfile

      - name: pnpm build
        run: pnpm --dir frontend build

      - name: go tool templ generate
        run: go tool templ generate

      - name: go test
        run: go test -race ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v4

      - name: pnpm install
        run: pnpm --dir frontend install --frozen-lockfile

      - name: pnpm build
        run: pnpm --dir frontend build

      - name: go tool templ generate
        run: go tool templ generate

      - name: go build
        run: go build ./...

      - name: goreleaser check
        run: goreleaser check
